### ISSUE TITLE
Updated list of interactions GloBI understands?

### ISSUE THREAD

**Issue by seltmann** [ParasiteTracker/GloBI-Biotic-Interaction-Relationships#1]
@jhpoelen I wonder if we can update this list

**Comment by jhpoelen** [comment]
An up-to-date list can be found via https://globalbioticinteractions.org/parasitetracker https://www.globalbioticinteractions.org/parasitetracker/#supported-terms and https://github.com/globalbioticinteractions/globalbioticinteractions/blob/master/eol-globi-lib/src/main/resources/org/globalbioticinteractions/interaction_types_ro.csv . 

Please re-open if more information is needed.
